#!/bin/bash
#
aeg=`date | cut -c12-13`
#
if test $aeg -ge 6 -a $aeg -lt 12
then
	echo "Tere hommikust, $USER!"
elif test $aeg -ge 12 -a $aeg -lt 18
then
	echo "Tere päevast, $USER!"
elif test $aeg -ge 18 -a $aeg -lt 22
then
	echo "Tere õhtust, $USER!"
elif test $aeg -ge 22 -a $aeg -le 24
then
	echo "Head ööd, $USER!"
elif test $aeg -ge 0 -a $aeg -lt 6
then
	echo "Head ööd, $USER!"
else
	echo "Vigane sisend"
fi
#
