#!/bin/bash
#
echo -n "Sisesta oma ees- ja perekonnanimi: " # väljastab teksti
read eesnimi perenimi # küsib kasutaja käest eesnime ja perenime
echo "Tere tulemast, $eesnimi $perenimi" # väljastab kasutaja sisestatud eesnime ja perenime koos tervitusega
#
# skripti lõpp
