#!/bin/bash
#
echo -n "Sisesta oma ees- ja perekonnanimi: " # väljastab teksti
read eesnimi perenimi # küsib kasutaja käest eesnime ja perenime
echo "Sinu eesnimi on $eesnimi ja sinu perenimi on $perenimi" # väljastab kasutaja sisestatud eesnime ja perenime koos tekstiga
#
# skripti lõpp
